<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/4/20/020
 * Time: 21:22
 */

namespace Shenxianshop\Modules\Back\Controllers;


class AdminLoginBase extends ControllerBase
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        if(!$this->session->get('admin')){
            $this -> flashSession -> error( $this->messages['lang_login'] );
            $this->cookies->set('url','/back/admin/login');//跳转的路径
            $this->response->redirect( '/back/admin/index' );

        }else{
            $this->view->setVar('admin',$this->session->get('admin'));
        }
    }
}