<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/4/20/020
 * Time: 21:22
 */

namespace Shenxianshop\Modules\Back\Controllers;


class AdminLoginBaseController extends ControllerBase
{
    public function initialize()
    {

        parent::initialize(); // TODO: Change the autogenerated stub
        if(!$this->session->get('admin')){
            $this -> flashSession -> error(  '登陆失败 '  );
            $this->response->redirect( '/backend/admin/login' );

        }else{
            $this->view->setVar('admin',$this->session->get('admin'));
        }
    }
}